const actions = {
  SET_STATE: 'wallets/SET_STATE',
  CHANGE_SETTING: 'wallets/CHANGE_SETTING',
  FETCH_WALLET_DATA: 'wallets/FETCH_WALLET_DATA',
  FETCH_SIDE_DATA: 'wallets/FETCH_SIDE_DATA',
  CHANGE_WALLET: 'wallets/CHANGE_WALLET',
  ADD_WALLET: 'wallets/ADD_WALLET',
  GET_PUBLIC_ADRESSES: 'wallets/GET_PUBLIC_ADRESSES',
  GET_NETWORK_STATE: 'wallets/GET_NETWORK_STATE',
  GET_VERIFIED_TOKENS_LIST: 'wallets/GET_VERIFIED_TOKENS_LIST',
  GET_EXCHANGE_RATES: 'wallets/GET_EXCHANGE_RATES',
  GET_UTXO_STATE: 'wallets/GET_UTXO_STATE',
  ENCRYPT_WALLET: 'wallets/ENCRYPT_WALLET',
  DECRYPT_WALLET: 'wallets/DECRYPT_WALLET',
  CHANGE_WALLET_NAME: 'wallets/CHANGE_WALLET_NAME',
  DELETE_WALLET: 'wallets/DELETE_WALLET',
  IMPORT_WALLET: 'wallets/IMPORT_WALLET',
  GET_STAKE_STATE: 'wallets/GET_STAKE_STATE',
  GET_POOLS_INFO: 'wallets/GET_POOLS_INFO',
  GET_STAKE_REWARDS_HISTORY: 'wallets/GET_STAKE_REWARDS_HISTORY',
}

export default actions
